spring:
  config:
    activate:
      on-profile: dev
# OpenAI
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:demo}
      model-name: gpt-4o-mini
      base-url: http://langchain4j.dev/demo/openai/v1
      temperature: 0.7             # 输出随机性（0~1）
      max-tokens: 4096             # 最大生成长度
      log-requests: true           # 打印请求日志
      log-responses: true

    streaming-chat-model:        # 流式调用模型
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: demo
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true

logging:
  level:
    dev.langchain4j: DEBUG       # 调试日志